@eventId = 12345678-1234-1234-1234-123456789012
@userId = 87654321-4321-4321-4321-210987654321

### Create Event
POST http://localhost:3000/api/events
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MjU5ODJjNi00ZDQ5LTQ2ZTEtYTY0OS1jZDAwNDA5YjY4MzciLCJpYXQiOjE3MjExMjI1MzksImV4cCI6MTcyMTEyNjEzOX0.lMLbidx6O2SLNsdz6qs_FK_9-6o56Yr0_sJvZ0HSIo8

{
  "title": "Concert",
  "description": "Live music event",
  "category": "Music",
  "location": "Stadium",
  "price": 50,
  "ticketsAvailable": 100,
  "date": "2024-12-31T23:59:59.000Z",
  "imageUrl": "http://example.com/image.jpg"
}

### Get All Events
GET http://localhost:3000/api/events

### Get Event by ID
GET http://localhost:3000/api/events/2bca9aa8-408c-4e8e-97c3-00fd49c2a317

### Update Event
PUT http://localhost:3000/api/events/2bca9aa8-408c-4e8e-97c3-00fd49c2a317
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MjU5ODJjNi00ZDQ5LTQ2ZTEtYTY0OS1jZDAwNDA5YjY4MzciLCJpYXQiOjE3MjExMjI1MzksImV4cCI6MTcyMTEyNjEzOX0.lMLbidx6O2SLNsdz6qs_FK_9-6o56Yr0_sJvZ0HSIo8
{
  "title": "Updated Concert",
  "description": "Updated live music event",
  "category": "Music",
  "location": "Stadium",
  "price": 60,
  "ticketsAvailable": 90,
  "date": "2024-12-31T23:59:59.000Z",
  "imageUrl": "http://example.com/new-image.jpg"
}

### Delete Event
DELETE http://localhost:3000/api/events/2bca9aa8-408c-4e8e-97c3-00fd49c2a317
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MjU5ODJjNi00ZDQ5LTQ2ZTEtYTY0OS1jZDAwNDA5YjY4MzciLCJpYXQiOjE3MjExMjI1MzksImV4cCI6MTcyMTEyNjEzOX0.lMLbidx6O2SLNsdz6qs_FK_9-6o56Yr0_sJvZ0HSIo8

### Book Ticket
POST http://localhost:3000/api/events/book
Content-Type: application/json

{
  "eventId": "2bca9aa8-408c-4e8e-97c3-00fd49c2a317",
  "userId": "35299e63-6fc7-4cb1-afc4-e67e1cea88c9",
  "ticketCount": 2
}

### Calculate Earnings
GET http://localhost:3000/api/events/2bca9aa8-408c-4e8e-97c3-00fd49c2a317/earnings
