### Buy or update ticket
POST http://localhost:3000/tickets/buy
Content-Type: application/json

{
  "userId": "b4cd8e79-bc6f-42fe-807a-0d70babe7da9",
  "eventId": "a67f3f7d-2136-4916-958d-5ca9fd746ed5",
  "ticketCount": 5
}

### Cancel ticket
DELETE http://localhost:3000/tickets/cancel/fe92fae4-5b56-4a35-8d48-9393fd2255c1

### Get all tickets for a user
GET http://localhost:3000/tickets/user/b4cd8e79-bc6f-42fe-807a-0d70babe7da9

### Get users with details for a specific event
GET http://localhost:3000/tickets/event/00b83e33-3b37-428b-822d-b795ed37c213/users

### Get all users with tickets
GET http://localhost:3000/tickets/users

### Calculate total money for all events
GET http://localhost:3000/tickets/total-money

### Calculate total money for a specific event
GET http://localhost:3000/tickets/event/a67f3f7d-2136-4916-958d-5ca9fd746ed5/total-money
