### buy ticket
POST http://localhost:3000/tickets/buy
Content-Type: application/json

{
  "userId": "5a48a5d7-b5c8-4709-9abd-18fd03e58cd1",
  "eventId": "2bca9aa8-408c-4e8e-97c3-00fd49c2a317",
  "ticketCount": 1
}

### cancel ticket
DELETE http://localhost:3000/tickets/cancel/fc208e31-7d72-4bfd-8a88-3178a22f20ac

### All tickets
GET http://localhost:3000/tickets/user/5a48a5d7-b5c8-4709-9abd-18fd03e58cd1

### Get users with details for specific event
GET http://localhost:3000/tickets/event/2bca9aa8-408c-4e8e-97c3-00fd49c2a317/users


# ### Get all users with tickets
# GET http://localhost:3000/tickets/users
