### Create User (POST /api/users)
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "whitneyjacks685@gmail.com",
  "password": "password123",
  "name": "jacks",
  "phoneNumber": "077839130",
  "image": "avatar.jpg",
  "isAdmin": false,
  "isManager": false
}

### Get All Users (GET /api/users)
GET http://localhost:3000/api/users

### Get User by ID (GET /api/users/:id)
GET http://localhost:3000/api/users/8b8de5bd-c363-45f6-a157-106b89add127

### Update User by ID (PUT /api/users/:id)
PUT http://localhost:3000/api/users/d5574577-940a-4dd1-835a-162c802fcbec
Content-Type: application/json

{
  "email": "updated.john.doe@example.com",
  "name": "Updated John Doe",
  "phoneNumber": "+9876543210",
  "isAdmin": true,
  "isManager": false
}

### Delete User by ID (DELETE /api/users/:id)
DELETE http://localhost:3000/api/users/e2a2d75e-ac9b-455e-8dc9-76684e72c43b
### Get Only Users (GET /api/users/role/users)
GET http://localhost:3000/api/users/role/users

### Get Only Admins (GET /api/users/role/admins)
GET http://localhost:3000/api/users/role/admins

### Get Only Managers (GET /api/users/role/managers)
GET http://localhost:3000/api/users/role/managers
